### ISSUE TITLE
턴제RPG게임

### ISSUE THREAD

**Issue by OrangeSnack** [slient13/CapstoneDesign#30]
## 기초시스템
   - [ ] 상태이상
   - [ ] 플레이어 스텟

## 장비창
- 시스템
  - [ ] 무기&방어구 장착
  - [ ] 무기 종류에 따른 전투스타일 반영
  - [ ] 장비템 능력치 반영
- 디자인
   - [ ] 장비창UI
   - [ ] 장비 아이콘

## 몬스터
- 시스템
   - [x] AI 아이들 움직임
   - [x] AI 플레이어 인식 움직임
   - [x] AI 맵 상호작용
- 디자인
   - [ ] 멧돼지 모델
   - [ ] "모션
   - [ ] 뱀 모델
   - [ ] "모션
   - [ ] 박쥐 모델
   - [ ] "모션

## 전투
- 시스템
   - [ ] 공격
   - [ ] 아이템 사용
   - [ ] 상태이상
   - [ ] 도주
   - [ ] 사망
   - [ ] 전투AI
- 디자인
   - [ ] UI

## 필드
   - [ ] 숲
   - [ ] 상호작용 가능 오브젝트

**Comment by OrangeSnack** [comment]
## 몬스터 AI 작업중
**볼드체**는 에디터에서 직접 수정 가능한 값

**대기시 행동 알고리즘**
1. 행동반경 트리거 배치
2. 몬스터한테 이동반경트리거 부착
3. **Float**초 후 이동트리거에서 랜덤 위치 픽업
4. 픽업한 위치가 행동반경 트리거 내부일경우 움직임 실행, 아닐시 다시 픽업 반복

**플레이어 발견 알고리즘**
1. 플레이어 발견 트리거 배치
2. 플레이어 발견 트리거 내부 진입시 **Float**초 후 플레이어 인식
3. 몬스터 마지막 저장위치 저장
4. 몬스터 위에 인식 아이콘 띄움 **Float**초 후 삭제
5. 플레이어 **Float**초동안 플레이어 위치로 쫒아감
6. 전투반경 트리거 진입시 전투Scene불러오기
7. 플레이어 도주 성공시 마지막 저장위치로 복귀

**Comment by ddrttl300** [comment]
BGM 및 효과음 사운드 파일 다운 완료

- 벨 소리 ( 할리갈리) 
- 몬스터에게 대결을 신청할때
- 숲 지형 BGM
- 승리시 효과음
- 전투 중

**Comment by ddrttl300** [comment]
뱀 몸통 모델링 완료 
박쥐 대신 이상한 몬스터 모델링 완료

모션구현은 아직 어려워서 모델링 급선무로 먼저 해보고 다시 천천히 해보겠음.
