### ISSUE TITLE
각 DB에 들어갈 요소 및 세부 사항(미완성)

### ISSUE THREAD

**Issue by Kwakhyunjong** [slient13/CapstoneDesign#32]
<DB 요소 및 세부 사항>

<플레이어 기본 정보(DB)>
1. 있어야 할 것: 플레이어 체력, 플레이어 피로도, 돈
2. 요구사항: 
플레이어의 체력은 아이템을 먹으면 증가
플레이어의 피로도는 잠을 자거나, 가만히 있으면 증가
돈은 보상으로 받거나, 아이템을 사고 팔때, 증가 및 감소
(자세한 증가 및 감소량은 아직 확실히 정하지는 못했습니다...ㅎ)

<R P G(DB)>
1. 있어야 할 것: 플레이어 체력, 몬스터 체력, 아이템, 장비, 보상
2. 요구사항: 
플레이어가 몬스터에게 맞았을 떄, 체력 -10 감소
플레이어가 몬스터를 때렸을 때, 몬스터 체력 -10감소
플레이어가 아이템을 먹으면, 플레이어 체력 +10 증가
플레이어가 장비를 착용하면, 착용한 장비의 종류가 기록되고, 그에 따른 공격력 및 방어력 증가
플레이어가 특정 몬스터를 잡으면, 그에 따른 보상 

<차량(DB)>
1. 있어야 할 것: 차량(오토바이, 자전거 등...), 플레이어 피로도, 기름(필요한 차량에 한해서), 속도  
2. 요구사항: 
플레이어가 차량을 타면, 해당 차량의 종류가 기록
플레이어가 한번 차량을 타고 이동하면, 플레이어 피로도 -10 감소
플레이어가 차량을 타고 이동하면, 해당차량의 기름 -20 감소
플레이어가 차량을 타고 이동할 때, 플레이어의 이동 속도 +10 증가
          
<거리미화(DB)>
1. 있어야 할 것: 쓰레기, 플레이어 피로도, 보상
2. 요구사항: 
플레이어가 쓰레기를 주울 때마다, 주운 쓰레기 개수 +1 증가
플레이어가 쓰레기를 주울 떄마다, 플레이어 피로도 -3 감소
플레이어가 일정 쓰레기 개수를 채우면, 그에 따른 보상 

 (자세한 증가 및 감소량은 아직 확실히 정하지는 못했고, 일단 요소들만 정해놨다고 보면 됩니다...ㅎ)

**Comment by Kwakhyunjong** [comment]
<최종 스탯 작성법>
- 플레이어 기본 스탯
작성법: 스탯명, 스탯 자료형, 초기값
ex)Hp, int, 100

- 차량 스탯
작성법: 스탯명, 스탯 자료형, 초기값, 설명
ex)MoterCycle, int, 0, 오토바이이다.

- 거리미화 스탯
작성법: 스탯명, 스탯 자료형, 초기값, 설명, 변동값
ex)Trash, int, 0, 쓰레기를 주운 횟수이다., Trash: 1(Trash값을 1씩 증가시킨다.)

- RPG 스탯

    1)장비
    작성법: 스탯명, 스탯 자료형, 초기값, 설명, 변동값
    ex)Weapon, int, 0, 무기입니다., Attack: 10(Attack값을 10씩 증가시킨다.)

    2)아이템
    작성법: 스탯명, 스탯 자료형, 초기값, 설명, 변동값
    ex)Hambuger, int, 0, 체력아이템입니다., Hp: 20(Hp값을 20씩 증가시킨다.)

    3)몬스터
    작성법: 스탯명, 스탯 자료형, 초기값, 설명, 변동값
    ex)MonHp, int, 100, 몬스터 체력이다., MonHp: -10(MonHp값을 10씩 감소시킨다.)

**Comment by Kwakhyunjong** [comment]
<각 DB별 요소>
- 플레이어 DB 요소
체력(기본, 최대, 최소), 피로도(기본, 최대, 최소), 돈(기본, 최소), 공격력(기본, 최대), 
방어력(기본, 최대), 쓰레기주운횟수

- 차량 DB 요소
오토바이, 자전거

- 거리미화 DB 요소
쓰레기를 주운 횟수, 피로도, 보상

-  RPG DB 요소
   1)장비
   무기, 방어구

   2)아이템
   햄버거, 콜라

   3)몬스터
   몬스터 체력

혹시 추가로 필요하다고 생각하는 요소들이 있다면 댓글 남기면 추가할게요.

**Comment by OrangeSnack** [comment]
### RPG 요소
**아이템**

|Name|Code|Type|Desc|Effect|Buy|Sell|
|-------|-----|-----|------|------|----|----|
|상처약|Med|int|사람이 써도 되나..?|HP+10|1000|800|
|멧돼지가죽|PLeather|int|튼튼한 멧돼지가죽이다|-|-|5000|
|단단한송곳니|PIvory|int|찔리면 몹시 아프게생겼다|-|-|10000|

**몬스터**

|Name|Code|Skills|SkillsDmg|HP|Damage|Drop|
|-------|-----|------|-----------|---|---------|------|
|멧돼지|W_Pig|{몸통박치기, 송곳니공격}|{1.0,1.6}|200|10|{멧돼지가죽,단단한송곳니}|

**Comment by Kwakhyunjong** [comment]
DB 테이블 작성
1. 플레이어 스탯 DB 테이블
2. 아이템 정보 DB 테이블
3. 차량 DB 테이블
4. 거리 미화 DB 테이블

<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>







&nbsp; | Code | Type | Default | Min | Max
-- | -- | -- | -- | -- | --
체력 | Hp | Int | 100 | 0 | 100
피로도 | Sp | Int | 0 | 0 | 100
돈 | Money | Int | 0 | 0 | -
공격력 | Attack | Int | 10 | 10 | -
방어력 | Defense | Int | 10 | 10 | -









<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>







&nbsp; | Code | Type | Name | Desc | Default | Effect | Buy | Sell
-- | -- | -- | -- | -- | -- | -- | -- | --
사과 | Apple | Int | 사과 | 잘 익은 사과다. | 0 | Hp:+10 | 1000 | 800
빵 | Bread | Int | 빵 | 갓 구운 빵이다. | 0 | Hp:+15 | 2000 | 1600
햄버거 | Hambuger | Int | 햄버거 | 군침이 도는 햄버거다. | 0 | Hp:+20 | 3000 | 2400
물 | Water | Int | 물 | 1급수 물이다. | 0 | Sp:-5 | 500 | 400
커피 | Coffee | Int | 커피 | 시원한 커피다. | 0 | Sp:-10 | 700 | 600
콜라 | Cola | Int | 콜라 | 톡 쏘는 콜라다. | 0 | Sp:-15 | 1000 | 900
무기 | Weapon | Int | 무기 | 장인이 만든 무기다. | 0 | Attack:+10 | 20000 | 15000
방어구 | Amor | Int | 방어구 | 장인이 만든 방어구다. | 0 | Defense:+10 | 30000 | 25000





<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>







&nbsp; | Code | Type | Desc | Default | Effect
-- | -- | -- | -- | -- | --
오토바이 | Motorcycle | 오토바이 | 꽤 비싼 오토바이다. | 0 | Sp: +20
자전거 | Bycycle | 자전거 | 두발 자전거이다. | 0 | Sp: +20






<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/Kwak/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>







&nbsp; | Code | Type | Desc | Default | Effect | Sell
-- | -- | -- | -- | -- | -- | --
종이 | Paper | Int | 무언가 적힌 종이이다 | 0 | Sp: +5 | 500
캔 | Can | Int | 누가 마시다 버린 캔이다. | 0 | Sp: +5 | 500
플라스틱 | Plastic | Int | 구겨진 플라스틱이다. | 0 | Sp: +5 | 500

**Comment by slient13** [comment]
https://github.com/slient13/CapstoneDesign/issues/32#issuecomment-844998511

지금 적힌 표만 가지고는 소모품과 장비를 구분할 수 없음.
소모품과 장비를 구분하기 위한 카테고리를 하나 새로 만들거나, 아니면 장비용 정보 규격을 따로 만들어줘라.

그리고 맨 아래 미화 관련 내용에서 'effect'는 사용 시 효과지 주울 때 페널티가 아님. 사용 시 효과지.
각 동작마다 소모하는 스테미너를 명시할꺼면 다른 방식을 이용해야 됨.
