### ISSUE TITLE
모델링 진행 상황

### ISSUE THREAD

**Issue by slient13** [slient13/CapstoneDesign#40]
![자전거](https://user-images.githubusercontent.com/37094635/119977512-812b7880-bff3-11eb-8c4e-998d2356a331.jpg)

**Comment by ddrttl300** [comment]
![Uploading KakaoTalk_20210528_195015328.jpg…]()

**Comment by ddrttl300** [comment]
![KakaoTalk_20210528_195015328](https://user-images.githubusercontent.com/65437401/119977666-afa95380-bff3-11eb-9794-db112225f6cd.jpg)
