### ISSUE TITLE
EquipmentUI 프리팹 업그레이드 요청

### ISSUE THREAD

**Issue by slient13** [slient13/CapstoneDesign#48]
## 요청 사항
- [x] 스크립트의 `Panel` 부분에 UI 패널(Equipment 라는 이름) 배정.
- [x] 우상단 X 버튼에 `EquipmentUI` 의 `CloseUI` 연결
- [x] 각 슬롯에 대한 altText 혹은 altImage 표시 기능을 위한 UI 오브젝트 추가.
- [x] 각 슬롯에 대한 상호작용 및 기능을 위한 UI 오브젝트 추가.
- [x] (선택) UI 우측 화면에 기능 적용.

## 비고
- 해당 요청은 장비 장착 해제 기능을 이용하기 위한 것이므로 슬롯을 통한 상호작용 기능의 구현이 가장 중요합니다.
- `EquipmentUI.cs` 파일을 수정할 필요가 있는 세부 동작은 제가 구현할 것이니 그것을 하기 위한 UI 기반만 수정해주면 됩니다. 단, 코드로 구현하는 것이 더 간편한 경우에는 해당 파일을 수정해도 상관은 없습니다.
- 슬롯 상호작용 부분은 InventoryUI 와 비슷하게 별도의 창을 띄우고자 하는 경우 별도의 UI 패널을 같이 포함시켜주시고, 그렇지 않다면 원하는 방식을 적어주시기 바랍니다.
- 우측 화면에 기능 적용이란 카메라를 연결할 것인지 별도의 플레이어 오브젝트를 띄우고 활용할 것인지 다른 방식을 쓸 것인지 등을 확실히 해달라는 것으로, 당장 급한 것은 아니기에 바로 할 필요는 없습니다.

**Comment by zzzxxxddd8** [comment]
EquipmentUI 브랜치 note에 new장비txt 같이 넣어놨음
